% ora, se nessuno cambia le carte in tavola (:@@@@@@@@@) , 
% i path sono fatti tutti allo stesso modo. cambia solo la cartella locale
% per ciascun ratto.

function ADDRESSES = AddressExercize(data)
               % identificativo esercizio   % indirizzo cartella raw data   
   ADDRESSES = {% Beast
                '2cRW' ,                     [data.rat_folder, '/2cRW/Neural_RAW']; ...                  
                % HEALTHY
                'BipCRW' ,                   [data.rat_folder, '/BipCRW/Neural_RAW']; ...  
                'BipRW' ,                    [data.rat_folder, '/BipRW/Neural_RAW']; ...  
                'BipRWINI' ,                 [data.rat_folder, '/BipRWINI/Neural_RAW']; ...  
                'BipSTAIRS',                 [data.rat_folder, '/BipSTAIRS/Neural_RAW']; ...  
                'BipTM' ,                    [data.rat_folder, '/BipTM/Neural_RAW']; ... 
                'QTM',                       [data.rat_folder, '/QTM/Neural_RAW']; ...
                'QCRW45',                    [data.rat_folder, '/QCRW45/Neural_RAW']; ...
                'QCRW90',                    [data.rat_folder, '/QCRW90/Neural_RAW']; ...  
                'QCRW',                      [data.rat_folder, '/QCRW/Neural_RAW']; ...  
                'QRW',                       [data.rat_folder, '/QRW/Neural_RAW']; ...
                'QRWINI',                    [data.rat_folder, '/QRWINI/Neural_RAW']; ... 
                'QSTAIRS',                   [data.rat_folder, '/QSTAIRS/Neural_RAW']; ...
                'Qlad',                      [data.rat_folder, '/Qlad/Neural_RAW']; ...                   
                'QrobRW',                    [data.rat_folder, '/QrobRW/Neural_RAW']; ... 
                'Qroblad',                   [data.rat_folder, '/Qroblad/Neural_RAW']; ...  
                'Surprise',                  [data.rat_folder, '/Surprise/Neural_RAW']; ...  
                % INJURIED
                'InjQCRW90',                 [data.rat_folder, '/InjQCRW90/Neural_RAW']; ...   
                'InjQRW',                    [data.rat_folder, '/InjQRW/Neural_RAW']; ...   
                'InjQRWROB',                 [data.rat_folder, '/InjQRWROB/Neural_RAW']; ...                   
               };          

           
      % HEALTHY     
          % BipCRW
          % BipRW
          % BipRWINI
          % BipSTAIRS
          % BipTM
          % QTM
          % QCRW45
          % QCRW90
          % QCRW
          % QRW
          % QRWINI
          % QSTAIRS
          % Qlad
          % QrobRW   
          % Qroblad       
          % Surprise
      % INJURIED
          % InjQCRW90
          % InjQRW
          % InjQRWROB